# Generated by Django 5.2.9 on 2025-12-14 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tutors", "0003_add_tutor_catalog_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("scheduled_at", models.DateTimeField(help_text="When the lesson is scheduled")),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(default=60, help_text="Lesson duration in minutes"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        help_text="Current status of the booking",
                        max_length=20,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, help_text="Price at the time of booking", max_digits=10
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", help_text="Additional notes from student"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        help_text="The student who made the booking",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        help_text="The tutor for this booking",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="tutors.tutor",
                    ),
                ),
            ],
            options={
                "db_table": "bookings",
                "ordering": ["-scheduled_at"],
                "indexes": [
                    models.Index(
                        fields=["tutor", "scheduled_at"], name="bookings_tutor_i_a4cf82_idx"
                    ),
                    models.Index(
                        fields=["student", "scheduled_at"], name="bookings_student_04ede5_idx"
                    ),
                    models.Index(fields=["status"], name="bookings_status_51373b_idx"),
                ],
            },
        ),
    ]
