# Generated by Django 5.2.9 on 2025-12-21 20:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("aggregate_type", models.CharField(db_index=True, max_length=50)),
                ("aggregate_id", models.CharField(db_index=True, max_length=50)),
                ("event_type", models.CharField(db_index=True, max_length=50)),
                ("payload", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("published_at", models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["published_at", "created_at"], name="events_outb_publish_bd6872_idx"
                    ),
                    models.Index(
                        fields=["aggregate_type", "published_at"],
                        name="events_outb_aggrega_56b2d1_idx",
                    ),
                ],
            },
        ),
    ]
