# Generated by Django 5.2.9 on 2025-12-14 19:59

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutors", "0002_add_tutor_draft"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutor",
            name="formats",
            field=models.JSONField(
                default=list, help_text="Teaching formats: ['online', 'offline']"
            ),
        ),
        migrations.AddField(
            model_name="tutor",
            name="location",
            field=models.CharField(
                blank=True, default="", help_text="City or region", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="tutor",
            name="rating",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Average rating from 0 to 5",
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("5")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="tutor",
            name="reviews_count",
            field=models.PositiveIntegerField(default=0, help_text="Number of reviews"),
        ),
        migrations.AddField(
            model_name="tutor",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-friendly identifier for the tutor",
                max_length=100,
                unique=True,
            ),
        ),
    ]
